version: '3.8'

# Raspberry Pi may only support docker-compose version 3.3
# version: '3.3'

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'airflow'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["airflow", "webserver"]
    environment:
      PYTHONPATH: /home
      AIRFLOW_HOME: /home
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home
    depends_on:
      - db
    command: ["airflow", "scheduler"]
    environment:
      PYTHONPATH: /home
      AIRFLOW_HOME: /home

volumes:
  postgres_data: