FROM python:3.7

WORKDIR /home

RUN apt update && apt install -y \
    libatlas-base-dev

###################
# Python packages #
###################

COPY requirements.txt /home

RUN pip install --extra-index-url=https://piwheels.org/simple -r requirements.txt
